# -*- coding: utf-8 -*-
"""AI Personal Assistant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16lSklV0AqZ4fh2W5JmF6NarJ-nbgbr9x
"""

! pip install gTTS

pip install -q -U google-generativeai

import pathlib
import textwrap
import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown
from gtts import gTTS
from IPython.display import Audio, display


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

#Start searching with google gemini
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API')
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-pro')

#create a function to ask question
def ask_question(name):
  ques = "Hey" + name + "what do you want?"
  ques = input("Hey," + name + " How can I help you? ")
  return ques

#Types of questions classification
def classify_questions(ques):
  goahead_with_google_search = False
  device_lst = ["alarm", "reminder", "call", "message"]
  personal_lst = ["who are you?", "who created you?"]

  device = False

  for i in device_lst:
    if i in ques:
      device = true

  if device:
    print("This question is related to device things, which is not supported in our google assistant ")

  personal_ques = False
  for i in personal_lst:
    if i in ques.lower():
      personal_ques = True

  if personal_ques:
    print("I am Jarvis. I am created by you ")


  if device:
    goahead_with_google_search = False
  elif personal_ques:
    goahead_with_google_search = False
  else:
    goahead_with_google_search = True

  return goahead_with_google_search

classify_questions("who are you?")

def ask_gemini(ques):
  response = model.generate_content(ques)
  to_markdown(response.text)
  return response.text

def get_audio(answer):
  tts = gTTS(answer)
  tts.save('audio.mp3')
  display(Audio('audio.mp3', autoplay=True))

do_you_need_more_help = "yes"
name = " "
while do_you_need_more_help == "yes":

  if name == " ":
    name = input("Hey what is your name ? ")

  q = ask_question(name)

  go_ahead = classify_questions(q)
  answer = ""

  if go_ahead == True:
    answer = ask_gemini(q)
    get_audio(answer)
    print(answer)

  do_you_need_more_help = input("Do you have any other questions ??")

print('Thanks for using me!!!')